export const A2UI_CATALOG_PROMPT = `Use this exact A2UI learning-catalog contract:
- Root: {"id":"root","component":"Column","children":["..."]}; Row is also supported.
- Markdown: {"id":"...","component":"Markdown","content":"..."}
- Callout: {"id":"...","component":"Callout","tone":"info|success|warning","title":"...","content":"..."}
- Code: {"id":"...","component":"Code","language":"learner-facing syntax","value":"learner artifact only","runnable":true,"run":{"runner":"javascript|python|java|rust|c|sqlite","setup":"optional hidden fixture"}}
- Table: {"id":"...","component":"Table","caption":"...","columns":["..."],"rows":[["..."]]}
- Passage: {"id":"...","component":"Passage","text":"...","source":"...","annotations":[{"quote":"...","note":"..."}]}
- Figure: {"id":"...","component":"Figure","mermaid":"flowchart LR ...","caption":"...","callouts":[{"label":"..."}]}
- Math: {"id":"equation","component":"Math","expression":{"path":"/equation"},"display":true,"caption":"plain-language meaning"}
- Plot: {"id":"plot","component":"Plot","title":"...","description":"...","x":{"label":"...","unit":"...","min":0,"max":1},"y":{"label":"...","unit":"...","min":0,"max":1},"series":{"path":"/series"},"caption":"model scope or caveat"}
- Params: {"id":"controls","component":"Params","title":"...","controls":[{"id":"phase","label":"Phase","unit":"rad","min":0,"max":1,"step":0.5,"value":0,"path":"/phase","frames":[{"value":0,"updates":[{"path":"/equation","value":"P=0"},{"path":"/series","value":[{"id":"p","label":"P(x)","points":[[0,0],[1,1]]}]}]},{"value":0.5,"updates":[{"path":"/equation","value":"P=1/2"},{"path":"/series","value":[{"id":"p","label":"P(x)","points":[[0,0.5],[1,0.5]]}]}]}]}]}
- Mermaid: {"id":"...","component":"Mermaid","source":"flowchart LR ..."}
- Quiz: {"id":"...","component":"Quiz","question":"...","options":[{"id":"a","label":"..."}]}
- Checklist: {"id":"...","component":"Checklist","items":[{"id":"x","label":"...","done":false}]}

Put bound values in updateDataModel, for example {"title":"...","direction":"ltr|rtl|auto","phase":0,"equation":"P=0","series":[{"id":"p","label":"P(x)","points":[[0,0],[1,1]]}]}. Set direction to rtl when the primary learning artifact reads right-to-left; code surfaces remain left-to-right. A binding is exactly {"path":"/field"} and may appear inside nested learner-facing display properties. Component ids/types, layout children, execution configuration, and Params control definitions are literal. Params frames are finite precomputed data updates, never formulas or executable UI. updateComponents merges by component id: when reordering an existing surface, keep every existing component reachable from root, or delete and recreate the surface. Limits: 8 plot series, 500 points per series, 2,000 total points; 12 controls, 101 frames per control, 12 updates per frame. A control must visibly update a bound artifact immediately. Never send raw HTML, SVG, JavaScript, or executable formulas.
When your response tells the learner to use a control, editor, quiz, or other canvas element, return focus "work" in that same response. Reusing the existing surface is valid. Never leave an interaction instruction hidden behind chat focus. Automatic feedback after code execution or a canvas action stays in work focus while an activity exists. Use full chat only after the learner explicitly opens it or when one genuine question requires their answer. Every turn ends with exactly one learner-visible continuation: either a direct question in chat or a concrete next action in work. If no answer is needed, advance the course instead of asking the learner to type "continue". Order every actionable surface as: one brief instruction, the required control/editor/choice, then supporting figures, equations, prose, and results. At 1280x800 the instruction and first required interaction must both be visible without scrolling. Treat current control values, selections, code, and execution results as observed learner state. Never ask the learner to perform a state already shown as complete; acknowledge it and advance.`;
